# Generated by Django 4.1.5 on 2023-02-03 13:47

from django.db import migrations, models
import publik.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('uses', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(default=publik.utils.custom_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='thumbnails')),
                ('level', models.CharField(choices=[('Begginner', 'Begginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Begginner', max_length=20)),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=20)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
